# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: v2.2.4
_src_path: gh:FallingColors/hexdummy
advanced: false
description: Making hexcasting more automation-friendly since 2026
display_name: Hexdustry
github_repo: hexdustry
github_user: whynotdogie
java_package: dev.dogie.hexdustry
mappings_name: Mojmap
minecraft_version_in_mod_version: true
mit_license: true
mod_version: 0.1.0
modid: hexdustry
